server:
  name: rooftop-gateway
  port: 80

spring:
  profiles:
    active: product

rooftop:
  server:
    identity:
      host: identity.rooftopmsa.org
      url: http://192.168.35.190:8080
      default-url: /v1/users

