server:
  name: rooftop-gateway
  port: 80

spring:
  profiles:
    active: product
  application:
    name: rooftop-gateway

rooftop:
  server:
    identity:
      host: identity.rooftopmsa.org
      url: http://192.168.35.190:8080
      default-url: /v1/users

management:
  endpoints:
    web:
      exposure:
        include: prometheus
  metrics:
    tags:
      application: ${spring.application.name}
