spring:
  profiles:
    active: product
  server:
    name: rooftop-gateway
    port: 80

rooftop:
  server:
    identity:
      host: identity.rooftopmsa.org
      url: http://192.168.35.190
      default-url: /v1/users

